<a href="https://colab.research.google.com/github/harish-03-11/Spam-email-prediction/blob/main/Spam_mail_deduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import pandas as pd
import numpy as np
import seaborn as sns

In [30]:
df = pd.read_csv("/content/sample_data/spam.csv")

In [31]:
df.sample(3)

Category                                            Message
1802      ham                           I wanna watch that movie
2386     spam  Someone has contacted our dating service and e...
5225      ham  Smile in Pleasure Smile in Pain Smile when tro...

In [32]:
df.isnull().sum()

Category    0
Message     0
dtype: int64

In [33]:
df.dropna(inplace = True)

In [34]:
df['target'] = df['Category'].apply(lambda x : 1 if x=='spam' else 0 )

In [35]:
df.sample(5)

Category                                            Message  target
3147      ham  SHIT BABE.. THASA BIT MESSED UP.YEH, SHE SHUDV...       0
4949     spam  Hi this is Amy, we will be sending you a free ...       1
5110     spam    You have 1 new message. Please call 08715205273       1
1788      ham                         Yes:)sura in sun tv.:)lol.       0
1442      ham                         Ya:)going for restaurant..       0

In [36]:
df.drop("Category", axis = 1)

Message  target
0     Go until jurong point, crazy.. Available only ...       0
1                         Ok lar... Joking wif u oni...       0
2     Free entry in 2 a wkly comp to win FA Cup fina...       1
3     U dun say so early hor... U c already then say...       0
4     Nah I don't think he goes to usf, he lives aro...       0
...                                                 ...     ...
5567  This is the 2nd time we have tried 2 contact u...       1
5568               Will ü b going to esplanade fr home?       0
5569  Pity, * was in mood for that. So...any other s...       0
5570  The guy did some bitching but I acted like i'd...       0
5571                         Rofl. Its true to its name       0

[5572 rows x 2 columns]

In [37]:
X = df['Message']
y = df['target']

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer

In [47]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.25, random_state = 5)

In [48]:
v = CountVectorizer()

In [49]:
x_train_values = v.fit_transform(X_train.values)

In [50]:
print(x_train_values.toarray()[:2])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [51]:
model = MultinomialNB()

In [52]:
x_train_nb = model.fit(x_train_values, y_train)

In [63]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'there you go click on this link for bonus cash rewards'
]

In [64]:
email_values = v.transform(emails)

In [65]:
model.predict(email_values)

array([0, 1])

In [ ]:
#Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!